services:
  - type: web
    name: bookmyshow-backend
    env: node
    buildCommand: yarn install && yarn build:tsc
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
